name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: Amazon-Linux

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_EC2 }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY_EC2 }}
          script: |
            sudo yum update -y 
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            cd home
            sudo mv * /var/www/html
